program/scm/apps/apis/urls.py
from django.conf.urls import url, include
from apps.apis.views import job_count, course_record
from apps.student import views

urlpatterns = [
    url(r'^job_count/$', job_count, name='job_count'),
    url(r'^course_record/(\d+)/$', course_record, name="course_record"),
    url(r'^homework/(\d+)/$', views.homework, name='homework')
]

program/scm/apps/student/urls.py
from django.conf.urls import url, include
from apps.student import views

urlpatterns = [
    url(r'^course/$', views.course, name='course'),
]

program/scm/scm/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from apps.crm import views
from apps.count.views import job_info


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/$', views.index, name='index'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^login/$', views.login, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^student/', include('apps.student.urls', namespace='student')),
    url(r'^teacher/', include('apps.teacher.urls', namespace='teacher')),
    url(r'^apis/', include('apps.apis.urls', namespace='apis')),
    url(r'^job_count/', views.job_count, name='job_count'),
    url(r'count/', include('apps.count.urls', namespace='count')),
    url(r'^test_session/', views.test_session, name='test_session'),
    url(r'^test_celery/', views.test_celery, name='test_celery'),
    url(r'test_transaction', views.test_transaction, name='test_transaction')
]

program/scm/apps/student/models.py
from django.db import models

# Create your models here.

program/scm/apps/student/views.py
from django.shortcuts import render, HttpResponse
from apps.crm.models import CourseRecord, ScoreRecord
from apps.crm.forms import HomeWorkForm
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required
def course(request):
    # item = CourseRecord.objects.all()
    try:
        st = request.user.related_student
        contents = st.my_class.related_course_record.all()
    except Exception as ex:
        contents = ""
    print(contents)
    kwgs = {
        "course_records": contents
    }
    return render(request, 'student/course.html', kwgs)

@login_required
def homework(request, course_record_id):
    if request.method == 'POST':
        print(request.FILES)
        form = HomeWorkForm(request.POST, request.FILES)
        if form.is_valid():
            print('data ok')
            student = request.user.related_student
            course_record = CourseRecord.objects.get(pk=course_record_id)
            score_record = ScoreRecord.objects.filter(student=student, course_record=course_record)
            homework_replay_content = form.cleaned_data['homework_replay_content']
            homework_replay_attach = form.cleaned_data['homework_replay_attach']
            if score_record:
                score_record = score_record.first()
                print('*'*10)
                print(score_record)
                score_record.homework_replay_content = homework_replay_content
                score_record.homework_replay_attach = homework_replay_attach
                score_record.save()
            else:
                score_record = ScoreRecord(student=student, course_record=course_record,
                                         homework_replay_content=homework_replay_content,
                                         homework_replay_attach=homework_replay_attach)
                score_record.save()
                print(student, course_record)
        else:
            print('data error')
        kwgs = {'form': form}
    else:
        form = HomeWorkForm()
        kwgs = {'form': form}

    return render(request, 'student/homework.html', kwgs)




program/scm/templates/student/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div class="col-sm-6">
        <section class="panel">
          <header class="panel-heading no-border">
              Border Table
          </header>
          <table class="table table-bordered">
              <thead>
              <tr>
                  <th>#</th>
                  <th>First Name</th>
                  <th>Last Name</th>
                  <th>Username</th>
              </tr>
              </thead>
              <tbody>
              <tr>
                  <td rowspan="2">1</td>
                  <td>Mark</td>
                  <td>Otto</td>
                  <td>@mdo</td>
              </tr>
              <tr>
                  <td>Mark</td>
                  <td>Otto</td>
                  <td>@TwBootstrap</td>
              </tr>
              <tr>
                  <td>2</td>
                  <td>Jacob</td>
                  <td>Thornton</td>
                  <td>@fat</td>
              </tr>
              <tr>
                  <td>3</td>
                  <td colspan="2">Larry the Bird</td>
                  <td>@twitter</td>
              </tr>
              </tbody>
          </table>
        </section>
    </div>
</body>
</html>

program/scm/templates/student/course.html
{% extends "crm/sub_page/base.html" %}
{% block content %}
    <div class="col-sm-6">
    {% if course_records %}
        <section class="panel">
          <header class="panel-heading no-border">
              {{ course_records.0.class_name }}
          </header>
          <table class="table table-bordered">
              <thead>
              <tr>
                  <th>#</th>
                  <th>课程名</th>
                  <th>课时名</th>
                  <th>上课时间</th>
                  <th>状态</th>
                  <th>操作</th>
              </tr>
              </thead>
              <tbody>
              {% for i in course_records %}
              <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ i.class_name.course.name }}</td>
                  <td>{{ i.course_content.name }}</td>
                  <td>{{ i.date }}</td>
                  <td>
                      {% if course_records.date %}
                          <span class="label label-default">已结束</span>
                      {% else %}
                          <span class="label label-primary">未开始</span>
                      {% endif %}
                  </td>
                  <td>
                      <!-- Button trigger modal -->
                        <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal" href="/apis/course_record/{{ i.id }}">
                          详
                        </button>
                  </td>
              </tr>
              {% endfor %}
              </tbody>
          </table>
        </section>
    {% else %}
        "您暂时没有报名任何课程，点......查看...."
    {% endif %}
    </div>

    <!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        ...hello world123123
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

program/scm/templates/student/course_record.html
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">Modal title</h4>
    </div>
    <div class="modal-body">
      {{ course_record.class_name }}
        <a href="{% url 'apis:homework' course_record.id %}">做作业</a>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      <button type="button" class="btn btn-primary">Save changes</button>
    </div>
  </div>
</div>

program/scm/templates/student/homework.html
{% extends 'crm/sub_page/base.html' %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.homework_replay_content }}<br/>
    {{ form.homework_replay_attach }}<br/>
    <button type="submit">提交</button>
</form>
{% endblock %}