program/scm/apps/count/urls.py
from django.conf.urls import url
from apps.count.views import job_info, jobinfo

urlpatterns = [
    url(r'^job_info/$', job_info, name="job_info"),
    url(r'^jobinfo/$', jobinfo, name='jobinfo')
]

program/scm/scm/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from apps.crm import views
from apps.count.views import job_info


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/$', views.index, name='index'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^login/$', views.login, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^student/', include('apps.student.urls', namespace='student')),
    url(r'^teacher/', include('apps.teacher.urls', namespace='teacher')),
    url(r'^apis/', include('apps.apis.urls', namespace='apis')),
    url(r'^job_count/', views.job_count, name='job_count'),
    url(r'count/', include('apps.count.urls', namespace='count')),
    url(r'^test_session/', views.test_session, name='test_session'),
    url(r'^test_celery/', views.test_celery, name='test_celery'),
    url(r'test_transaction', views.test_transaction, name='test_transaction')
]

program/scm/templates/job/job_count.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta charset="utf-8"><link rel="icon" href="https://static.jianshukeji.com/highcharts/images/favicon.ico">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style>
            /* css 代码  */
        </style>
        <script src="https://img.hcharts.cn/jquery/jquery-1.8.3.min.js"></script>
        <script src="https://img.hcharts.cn/highcharts/highcharts.js"></script>
        <script src="https://img.hcharts.cn/highcharts/modules/exporting.js"></script>
        <script src="https://img.hcharts.cn/highcharts-plugins/highcharts-zh_CN.js"></script>
    </head>
    <body>
        <div id="container" style="min-width:400px;height:400px"></div>
        <script>
            $.getJSON('http://127.0.0.1:8000/apis/job_count',
            function (data) {
               $(function () {
                    $('#container').highcharts({
                        chart: {
                            plotBackgroundColor: null,
                            plotBorderWidth: null,
                            plotShadow: false
                        },
                        title: {
                            text: '就业信息统计图'
                        },
                        tooltip: {
                            headerFormat: '{series.name}<br>',
                            pointFormat: '{point.name}: <b>{point.percentage:.1f}%</b>'
                        },
                        plotOptions: {
                            pie: {
                                allowPointSelect: true,
                                cursor: 'pointer',
                                dataLabels: {
                                    enabled: false
                                },
                                showInLegend: true
                            }
                        },
                        series: data
                    });
                });
           })
        </script>

​

program/scm/templates/job/job_info.html
{% extends 'crm/sub_page/base.html' %}
{% load staticfiles %}
{% block content %}
<h1>就业信息详情</h1>
    <div>薪水：
        <input name="username">
    </div>
    <table id="table"
               data-toggle="table"
               data-toolbar="#toolbar_jobinfo"
               data-height="460"
               data-query-params="queryParams"
               data-pagination="true"
               data-side-pagination="server"
               data-search="true"
               data-url="{% url 'count:job_info' %}"
               data-page-list="[10, 25, ALL]"
               data-page-size="5"
               data-show-refresh="true"
               data-show-toggle="true"
               data-show-export="true"
               data-export-types="['excel']"
               data-export-options='{
                 "fileName": "备件操作日志",
                 "worksheetName": "备件操作日志",
                 }'>
            <thead>
            <tr>
{#                <th data-field="id">ID</th>#}
                <th data-field="student__detail__real_name">姓名</th>
                <th data-field="company">公司</th>
                <th data-field="salary">薪水</th>
                <th data-field="position">岗位</th>
                <th data-field="job_photo">照片</th>
                <th data-field="oper"
                    data-formatter="operateFormatter"
                    data-events="operateEvents">操作</th>
            </tr>
            </thead>
        </table>


{% endblock %}
{% block loadjs %}
<script src="{% static 'bootstrap-table/bootstrap-table.min.js' %}" type="text/javascript"></script>
<script src="{% static 'bootstrap-table/tableExport.js' %}" type="text/javascript"></script>
<script src="{% static 'bootstrap-table/bootstrap-table-export.js' %}" type="text/javascript"></script>
<script>
    $(function(){
        $('.fixed-table-toolbar .search').removeClass('search').addClass('search2')
    })
    $table = $('#table');
    function  queryParams(tableParams) {
        var params = {};
        params['pagesize'] = tableParams.limit;
        params['offset'] = tableParams.offset;
        params['page'] = $table.bootstrapTable('getOptions').pageNumber;
        $('#toolbar_jobinfo').find('input[name]').each(
            function () {
                params[$(this).attr('name')] = $(this).val()
            }
        );
        return params
    }

    window.operateEvents = {
        'click .like': function (e, value, row) {
            alert('Like:'+JSON.stringify(row));
        },
        'click .remove': function (e, value, row) {
            names = [row['student__detail__real_name'],];
            alert(names)
            $table.bootstrapTable('remove', {field: 'student__detail__real_name', values: names})
        },
    };

    function operateFormatter(value, row, index) {
        return [
            '<a class="like" href="javascript:void(0)" title="Like">',
            '<i class="glyphicon glyphicon-heart"></i>',
            '</a>  ',
            '<a class="remove" href="javascript:void(0)" title="Remove">',
            '<i class="glyphicon glyphicon-remove"></i>',
            '</a>'
        ].join('');
    }


</script>
{% endblock %}

{% block loadcss %}
<link href="{% static 'bootstrap-table/bootstrap-table.min.css' %}" rel="stylesheet">
<style>
        .fixed-table-toolbar .search2 {
            position: relative;
            margin-top: 10px;
            margin-bottom: 10px;
            line-height: 34px;
        }
</style>
{% endblock %}